services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 10070:32400
    volumes:
      - /mnt/appserver/plex/config:/config
      - /mnt/media:/ponysmedia
    restart: unless-stopped