services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/appserver/nginx/data:/data
      - /mnt/appserver/nginx/certs:/custom-certs
      - /mnt/appserver/nginx/letsencrypt:/etc/letsencrypt